### ISSUE TITLE
Usage section in README should be updated.

### ISSUE THREAD

**Issue by marekdano** [jsjoeio/use-star-wars-quote#6]
The `Usage` section in README is not the same as it is on [NPM](https://www.npmjs.com/package/@jsjoeio/use-star-wars-quote)

I think in the README the section should be:
```javascript
import React from 'react'
import { useStarWarsQuote } from '@jsjoeio/use-star-wars-quote'
 
const App = () => {
  const { quote, loading } = useStarWarsQuote()
 
  if (loading) return <p>Loading...</p>
 
  if (quote) {
    return (
      <div>
        {quote}
      </div>
    )
  }
 
  return null
}
export default App
```

**Comment by jsjoeio** [comment]
You are absolutely right. I must have forgot to push locally. Just made the update. Thank you, @marekdano !
